#!/usr/bin/env ruby
# coding: utf-8

require 'thor'

class Count < Thor
  desc 'count','count : 文字列が含まれる行数と文字列の数を表示'
  method_option :find, type: :string, aliases: "-f", desc: "文字列が含まれる行数と文字列の数を表示"
  method_option :line, type: :string, aliases: "-l", desc: "文字列が含まれる行数を表示"
  method_option :count, type: :string, aliases: "-c", desc: "文字列の数を表示"
  
  def count(filename, search_word)
    line_co = 0
    word_co = 0
    
    if File.exist?(filename)
      file = open(filename, "r")

        file.each_line {|line|
          #文字列が含まれる行数をカウント
          line_co += 1 if line.index(search_word)
          
          #文字列の数をカウント(英単語のみ)
          words = line.scan(search_word)
          word_co += words.length
        }

      file.close
      
      #optionごとに表示を分ける
      if options[:find]
        puts "[line=#{line_co} : count=#{word_co}]"
      elsif options[:line]
        puts "[line=#{line_co}]"
      elsif options[:count]
        puts "[count=#{word_co}]"
      elsif ((line_co == 0) || (word_co == 0))
        puts "Illegal error"
      else
        puts "[line=#{line_co} : count=#{word_co}]"
      end
      
    else
      puts "No such file"
    end
  end  
end

Count.start